apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 295851827073.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 295851827073.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: ca7150f1
resources:
- ../../base
patches:
- path: front-deployment-patch.yaml
- path: front-service-patch.yaml
